server:
  port: 8080

spring:
  datasource:
    url: ${SPRING_DATASOURCE_URL}
    username: ${SPRING_DATASOURCE_USERNAME}
    password: ${SPRING_DATASOURCE_PASSWORD}

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true

# service communication
auth:
  service:
    url: ${AUTH_SERVICE_URL:http://localhost:8081}

tracking:
  service:
    url: ${TRACKING_SERVICE_URL:http://localhost:8082}

ai:
  service:
    url: ${AI_SERVICE_URL:http://localhost:8083}
